### ISSUE TITLE
TypeSafe<X> necessary now that we have strong mode?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/async#11]
Specifically, because the `as T` checks incur a runtime cost that can be caught statically now?

**Comment by nex3** [comment]
These were actually added *because of* strong mode. For example, there are situations where the type system can't prove that a given `Stream` is a `Stream<int>`. There's *also* no guarantee that its reified type parameter is `int`, so `stream as Stream<int>` isn't safe. But the user knows that in practice it will only ever emit ints. Now they can write `DelegatingStream.typed<int>(stream)` to safely produce a stream with the static and reified type of `Stream<int>`.

In the long term I think a lot of these should be pushed down into the core libraries as instance methods like `Stream<T> cast<T>()`, but I haven't started seriously pushing on that.
