### ISSUE TITLE
Ephemeral AsyncCache is not truly ephemeral

### ISSUE THREAD

**Issue by kentcb** [dart-lang/async#151]
Hi,

Here is a repro:

```dart
import 'package:async/async.dart';

Future<void> main(List<String> arguments) async {
  final cache = AsyncCache.ephemeral();

  final firstValue = await cache.fetch(_getValue);
  print('First value: $firstValue');
  final secondValue = await cache.fetch(_getValue);
  print('Second value: $secondValue');
}

int _value = 0;
Future<int> _getValue() async {
  await Future<void>.delayed(const Duration(milliseconds: 500));
  return ++_value;
}
```

This outputs:

```
First value: 1
Second value: 1
```

My expectation would be that the cached future would be invalidated immediately after the first `fetch` is awaited, leading to this output:

```
First value: 1
Second value: 2
```

The reason this doesn't happen is because an ephemeral `AsyncCache` has a `duration` of zero, but invalidation always uses a `Timer`, so invalidation won't occur until the event loop gets a chance to execute (after my `main`).

By making the following adjustments to `AsyncCache`, I get the desired behavior:

```dart
  Future<T> fetch(Future<T> Function() callback) async {
    if (_cachedStreamSplitter != null) {
      throw StateError('Previously used to cache via `fetchStream`');
    }

    var future = _cachedValueFuture;

    if (future == null) {
      future = _cachedValueFuture = callback();
      await future;
      _startStaleTimer();
    }

    return future;
  }

  void _startStaleTimer() {
    if (_duration == Duration.zero) {
      invalidate();
    } else {
      _stale = Timer(_duration, invalidate);
    }
  }
```
I believe `fetchStream` would require a tweak similar to that I made to `fetch`.

Am I right in thinking this is a bug, or is my expectation of behavior incorrect?

**Comment by nex3** [comment]
I don't think I'm the right assignee for this... I didn't write this code originally, @matanlurey did.

**Comment by lrhn** [comment]
The documentation does suggest that the value should be cleared immediately after a value has been produced, and it's only calls happening *during* the synchronous invocation which has the same future returned.

I'm also not sure what the original intent was. Allowing the cache to survive for zero milliseconds (rounded up) seems *fair*. If anything, it ensures that another request during the processing of the first response gets the same result again.

I wouldn't use `Duration.zero` as a trigger for instant invalidation, since someone might pass that value as an actual argument. Would probably make `_duration` nullable and use `null` as marker instead.
