### ISSUE TITLE
Future.wait() but with Records

### ISSUE THREAD

**Issue by navaronbracke** [dart-lang/async#226]
### Use case

When awaiting multiple `Future`s one can use `Future.wait([...])`. This is handy if all Futures have the same return type.
However, there are situations where the types do not match.

Consider the following code sample:

```
void main() async {
  // Can't use `Future.wait()` because the futures have different return types,
  // and using `Object` defeats the purpose of having a typed return value for each.
  // Instead, start both futures, but don't await them yet.
  // However, this code has the drawback of having to know why these futures are started early.
  // If someone else decides to write 'final res1 = await getFoo(); final res2 = await getBar();'
  // we lose the original intent of the code.
  final fut1 = getFoo();
  final fut2 = getBar();
  
  // Now we wait for both to complete.
  final res1 = await fut1;
  final res2 = await fut2;
  
  // do something with res1 and res2 
}

Future<int> getFoo() async {
  return 42;
}

Future<bool> getBar() async {
  return true;
}
```

### Proposal

Once we have Records, it would be nice if there was a utility method similar to `Future.wait()` that handles multiple different types.

I.e.

```
Future<Record<T>> waitWithRecord(Record<Future<T>> input) {
 return (
   for(final field in input.fields) await field,
 );
}
```

Open questions:
- Can we iterate over the fields of a record? (I don't see anything in the spec besides the individual getters)
- How do we define the input and output shapes for the respective records, in a generic way? There are no type literals for Records.
- Do we handle errors like how Future.wait() does it?

**Comment by lrhn** [comment]
I want this. I want this so much that I'll either add it to `package:async` or to `dart:async`.

We can't abstract over record shape, so the best we can do is to have a set of functions.
```dart
extension Wait2<A, B> on (Future<A>, Future<B>) {
  Future<(A, B)> get wait { ... }
}
extension Wait3<A, B, C> on (Future<A>, Future<B>, Future<C>) {
  Future<(A, B, C)> get wait { ... }
}
```
(I'm leaning towards making it `operator~()` instead, because `await (f1, f2).wait` feels backwards, and `await ~(f1, f2)` looks better. We decided against making `await (f1, f2)` auto-await both `f1` and `f2`, because it makes things weird if awaiting `FutureOr<(Future<int>, Future<int>)>`. Not that you should have that type, but we can't *prevent* it.)

**Comment by lrhn** [comment]
The landing stuck, so I think we can consider this a done deal. If not, we'll just have to reopen.
