### ISSUE TITLE
Dart 3 incompatibilty: `DelegatingStream<T> extends StreamView` but `StreamView` is `base class`

### ISSUE THREAD

**Issue by oprypin** [dart-lang/async#238]
```
The type 'DelegatingStream' must be 'base', 'final' or 'sealed' because the supertype 'StreamView' is 'base'.
Try adding 'base', 'final', or 'sealed' to the type.
class DelegatingStream<T> extends StreamView<T> {
      ^
```

https://github.com/dart-lang/async/blob/012781315e0f4659bc8d7806352e350e8fff8048/lib/src/delegate/stream.dart#L14

cc @lrhn @natebosch 

Base definition:
https://github.com/dart-lang/sdk/blame/fb43937e201b76a3a53cb5bb6a001b4c79463939/sdk/lib/async/stream.dart#L2180

**Comment by lrhn** [comment]
Maybe it was a mistake to make that one `base`.
Other similar classes have been transformed back to non-`base`, because it wasn't strictly *necessary*, and it annoyed subclass authors.

**Comment by natebosch** [comment]
Ah, I hadn't considered how a non-breaking change in the SDK could force down a breaking change on a package like this...

**Comment by natebosch** [comment]
> Having to write `base` on all subclasses isn't helping anyone.

I think it helps consumers of `DelegatingStream` in a similar way to `StreamView` - it guides towards correct usage.

This class doesn't have any reason to exist anymore in `async`. It would make me a little sad if we have to ship a sub-optimal SDK because of a legacy class in `async` that isn't providing any value to anyone.

I think this class looks like, where it has been used, it's mostly been used correctly. We could check more carefully for usage and add `base` without a major version bump in this package.

**Comment by lrhn** [comment]
The problem comes if someone creates a new interface, say `class StreamWithLatest<T> extends Stream<T> { T get latest; bool get hasLatest; StreamWithLatest(Stream<T> source) ... }`, which (makes no logical sense, but also) is both an implementation and valid interface that someone can implement in their own way.
_(You should never do that! Favor composition over inheritance! But it'll happen.)_

If they then decide to use `StreamView` as an implementation choice,
```dart
class StreamWithLatest<T> extends SteamView<T> {
  bool get hasLatest => ...
  T get latest => ...

  StreamWithLatest<T>(super.stream);

  StreamSubscription<T> listen(...) {
    // special implementation
  }
}
```
then they suddently *have* to make their `StreamWithLatest` class `base` and disallow people from implementing it.
For no good reason.

I'll remove the `base` from `StreamView`, and see if I can get it cherry-picked.
